# Generated by Django 5.1.6 on 2025-04-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='platform',
            field=models.CharField(blank=True, help_text='SNS種別やプラットフォーム名', max_length=100),
        ),
    ]
